sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
  - docker
  - redis
cache: pip
install:
  - pip install --upgrade pip setuptools wheel
script:
  - docker-compose build
  - docker-compose up --no-start
  - docker-compose start postgres
  - docker-compose run --rm server sh -c "/app/bin/wait-for-it.sh postgres:5432 -- python manage.py database create_tables"
  - docker-compose run --rm postgres psql -h postgres -U postgres -c "create database tests;"
  - docker-compose run server tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: emtwo
  distributions: sdist bdist_wheel
  password:
    secure: so1O847pZ9Szkgyx7QbpPwM7573OYzjoWqUmgUmi2mckVUiZqlg7XkhVoFugObvj8NagO6M9/UUD3SqzGkwxK2z+Kvt0l1SFlIlyT89PoVOZiVLAPJSoqJFSKdvosERDymuD4wwyh6qKyBEfZtn76Q8v8UpMHnGL06Qr4YM6fOLjjpVYHqX2Xi0X6m6P+klVR6qFcW84afKuLZHy1aX0+tcRyXTe7Skvq+rl5U9wkPjVXUrgC4miLmg6y3uFFtzIbLWsrO/lyyx6Mmx7JUri0TtTA0J3ueBoLn06kYvIFQ/yoAOCpS51cc9MN08xwwMEB5fr91t5GujZDPLBVcSI6eyO2KfAYOs0h++DqMqJ7BNQAzqvWmahekkWqpW+K9IuOp6DG79U090aFX+wp4d69u12pXFcuTgReUDqBPilt8kbf8gcjfOSxB0M4xwt7djow93ATXQLCm2+J7jgUyvaVRn1Lld+zm+RrbB/GHPRvWQjKQe5Z83Zm9XL7VwVVq0pX4i0NEQSum9MMqRJFeuSSim82hFjElt14ZjtH/MuJpTiyu5T9SF4wA8rciRtDXsxcnj4Gm3jmTz3CRMXPVSSRgqmDusmjv+h5gBTSjhO1Rw95NJ2hoWHpe8wDw5Qq0E9h4z+k+wAX+KoL/FlFGJSscazjP1pezai3YKunczHx1I=
  on:
    tags: true
    repo: mozilla/redash-stmo
